### ISSUE TITLE
Broken with mkosi version 8

### ISSUE THREAD

**Issue by bwidawsk** [pmem/run_qemu#1]
mkosi now requires a verb as part of the command invocation. From the docs, it looks like `build` is the correct verb to make everything behave as it did before.

**Comment by bwidawsk** [comment]
mkosi also now supports a distro option, `-d`. We could have something like `-d $distro`

**Comment by bwidawsk** [comment]
@stellarhopper  debugged this to Autologin added to the template

**Comment by stellarhopper** [comment]
We could either remove the autologin option, or add a README note that mkosi 9+ is expected.

**Comment by bwidawsk** [comment]
I think given that this is targeted in part toward people who have no clue what they're doing on a command line... the former is a better choice.

Option 3 would be to dynamically add to the config if mkosi >= 9
