### ISSUE TITLE
Arch needs meson package

### ISSUE THREAD

**Issue by bwidawsk** [pmem/run_qemu#10]
https://github.com/pmem/run_qemu/blob/926447ae8c30a14fa29a6744ad63bcd9dbf9e678/mkosi.arch.default.tmpl#L26

Too lazy to make a PR... Package is called "meson". This is fixes a regression caused by d4784769e63b37302c90e338ed255570754d6c45

As a side note, d4784769e63b37302c90e338ed255570754d6c45 also breaks older versions of ndctl. I don't think that needs fixing, but just mentioning...

**Comment by stellarhopper** [comment]
Yep agreed on older versions, hopefully that will become the distant past soon enough :)
For fedora I think I also had to install ninja-build. Do you need that as well, or just meson?

**Comment by bwidawsk** [comment]
> 

No. Installing meson pulls in ninja.
