### ISSUE TITLE
dracut-install crashing

### ISSUE THREAD

**Issue by davidlohr** [pmem/run_qemu#14]
While this is not a bug in this project, 'run_qemu.sh' has a way of always triggering dracut-install(1) segfaults during the install_build_initrd phase. I can reproduce this on every run in Fedora 36 and Tumbleweed, it can happen multiple times as well during the same phase.

```
/usr/lib/dracut/dracut-init.sh: line 1015: 1240336 Segmentation fault      (core dumped) "$DRACUT_INSTALL" ${initdir:+-D "$initdir"} ${dracutsysrootdir:+-r "$dracutsysrootdir"} ${loginstall:+-L "$loginstall"} ${hostonly:+-H} ${omit_drivers:+-N "$omit_drivers"} ${srcmods:+--kerneldir "$srcmods"} ${_optional:+-o} ${_silent:+--silent} -m "$@"
dracut: FAILED:  /usr/lib/dracut/dracut-install -D /var/tmp/dracut.EboI1Q/initramfs -N nfit|libnvdimm|nd_pmem --kerneldir ./qbuild/mkosi.extra/lib/modules/5.18.0/ -o -m fuse msr ipmi-devintf fuse ip_tables ip6_tables
```

**Comment by stellarhopper** [comment]
@davidlohr Interesting - I haven't seen that before, I'm on Fedora 36 too, with
```
$ dracut --version
dracut 056-1.fc36
```

**Comment by davidlohr** [comment]
Yup, same version of dracut as well.

fwiw here's the bt (albeit no debug symbols)

coredumpctl info 1240336
           PID: 1240336 (dracut-install)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 11 (SEGV)
     Timestamp: Fri 2022-06-03 12:29:37 PDT (35min ago)
  Command Line: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.EboI1Q/initramfs -N $'nfit|libnvdimm|nd_pmem' --kerneldir ./qbuild/mkosi.extra/lib/mo>
    Executable: /usr/lib/dracut/dracut-install
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-gnome-urxvt-720651.scope
          Unit: user@1000.service
     User Unit: app-gnome-urxvt-720651.scope
         Slice: user-1000.slice
     Owner UID: 1000 (dave)
       Boot ID: 7f64c9af6135476b90a9b9ae89bca563
    Machine ID: 87b61e48a59e48889b49ad43bf0d0db8
      Hostname: offworld
       Storage: /var/lib/systemd/coredump/core.dracut-install.0.7f64c9af6135476b90a9b9ae89bca563.1240336.1654284577000000.zst (present)
     Disk Size: 1.8M
       Message: Process 1240336 (dracut-install) of user 0 dumped core.
                
                Module linux-vdso.so.1 with build-id b4a17b6c642acd49fb6eea4e8a4b04bde1ea0e1f
                Module libcrypto.so.3 with build-id 757e4278094d2d0ffdaf399824ef5202f947d5ba
                Metadata for module libcrypto.so.3 owned by FDO found: {
                        "type" : "rpm",
                        "name" : "openssl",
                        "version" : "3.0.2-5.fc36",
                        "architecture" : "x86_64",
                        "osCpe" : "cpe:/o:fedoraproject:fedora:36"
                }
                
                Module libz.so.1 with build-id 624a44f31d31dd74964832dd5fbc005ec62d9ef3
                Metadata for module libz.so.1 owned by FDO found: {
                        "type" : "rpm",
                        "name" : "zlib",
                        "version" : "1.2.11-31.fc36",
                        "architecture" : "x86_64",
                        "osCpe" : "cpe:/o:fedoraproject:fedora:36"
                }
                
                Module liblzma.so.5 with build-id 99fa3343b2dad5a67bdb525e56367a260ae05df2
                Stack trace of thread 1240336:
                #0  0x00007f9566f9fb3b __vfprintf_internal (libc.so.6 + 0x6fb3b)
                #1  0x00007f9566fb206c __vsnprintf_internal (libc.so.6 + 0x8206c)
                #2  0x00007f956704f864 __snprintf_chk (libc.so.6 + 0x11f864)
                #3  0x00007f9566f1dc53 kmod_search_moddep (libkmod.so.2 + 0xac53)
                #4  0x00007f9566f201ff kmod_module_new_from_lookup (libkmod.so.2 + 0xd1ff)
                #5  0x00007f9566f208ca lookup_softdep (libkmod.so.2 + 0xd8ca)
                #6  0x00007f9566f21bec kmod_module_get_softdeps (libkmod.so.2 + 0xebec)
                #7  0x00005655308859c0 install_dependent_modules (dracut-install + 0x99c0)
                ...
                ELF object binary architecture: AMD x86-64

**Comment by marc-hb** [comment]
Is this still an issue? It's been 2 years now, I doubt anyone still cares about a 2 years old dracut...
