### ISSUE TITLE
ovmf install location

### ISSUE THREAD

**Issue by photoszzt** [pmem/run_qemu#30]
I'm trying to use this script to build the VM and get an error message: OVMF binaries not found, please install 'edk2-ovmf' or similar
The distro I'm using is ubuntu 22.04 and install the OVMF package. I have the following: 
```
ls /usr/share/ovmf/
OVMF.fd  PkKek-1-snakeoil.key  PkKek-1-snakeoil.pem
```
https://github.com/pmem/run_qemu/blob/31cb2d0b796a15a405497734b372de4ffba27bd6/run_qemu.sh#L986-L991
I'm not sure whether what I have are equivalent to the files listed here. I only have one fd file not CODES.fd and VARS.fd.

**Comment by stellarhopper** [comment]
@photoszzt Ah this looks like it's because Ubuntu places the files we need in /usr/share/OVMF.

I've pushed a fix - can you retry with the latest main?

**Comment by photoszzt** [comment]
@stellarhopper It's working for me now. Thanks for the fix.
