### ISSUE TITLE
Error: Workspace command kernel-install add 6.5.0 /lib/modules/6.5.0/vmlinuz returned non-zero exit code 1.

### ISSUE THREAD

**Issue by yizhanglinux** [pmem/run_qemu#37]
Hello

Running run_qemu with [1] failed at [2], could anyone help check it?
And could you help provide the workable environment, so I can try with them.

[1]
```
DISTRO: Fedora release 39 (Thirty Nine) with 6.5.0-0.rc7.20230821gitf7757129e3de.50.fc39.x86_64
Linux: latest linux tree: https://github.com/torvalds/linux.git
mkosi: mkosi-14-5.fc39.noarch
```

[2]
```
#run_qemu.sh --cxl
--snip--
‣      Unmounting API VFS…
‣    Unmounting Package Cache
‣    Setting root password
‣    Setting up autologin…
‣    Removing random seed
‣   Unmounting image…
‣  Detaching /dev/loop0
‣  Installing cache copy…
‣  Installed cache copy root.img.cache-pre-inst
‣  Changing ownership of output file /root/git/linux/qbuild/root.img.cache-pre-inst to user root…
‣  Changed ownership of /root/git/linux/qbuild/root.img.cache-pre-inst
‣ Running second (final) stage…
‣  Basing off cached image /root/git/linux/qbuild/root.img.cache-pre-inst
‣  Copied cached image as /root/git/linux/qbuild/.mkosi-i88mczn7
‣  Refreshing partition table…
Partition #1 contains a vfat signature.
Partition #2 contains a ext4 signature.
‣  Refreshed partition table.
‣  Attaching /root/git/linux/qbuild/.mkosi-i88mczn7 as loopback…
‣   Refreshing file system /dev/loop0p2…
tune2fs 1.47.0 (5-Feb-2023)
‣   Mounting image…
‣    Copying in extra file trees…
‣    Generating initramfs images…
/usr/bin/dracut: line 1056: /sys/module/firmware_class/parameters/path: No such file or directory
dracut: No '/dev/log' or 'logger' included for syslog logging
/usr/bin/dracut: line 1056: /sys/module/firmware_class/parameters/path: No such file or directory
dracut: No '/dev/log' or 'logger' included for syslog logging
cp: error writing '/efi/99d5c5d911e74e8192390fba2a07d2a2/6.5.0/initrd': No space left on device
dracut: Creation of /efi/99d5c5d911e74e8192390fba2a07d2a2/6.5.0/initrd failed
‣ Error: Workspace command kernel-install add 6.5.0 /lib/modules/6.5.0/vmlinuz returned non-zero exit code 1.
```

**Comment by stellarhopper** [comment]
@yizhanglinux Looks like you just ran out of space on the guest image. This can happen if you add a few different kernel builds worth of lib/modules/* - in that case you can try nuking the image and starting from scratch with a '-r wipe'.

If the image size does need to grow (i.e. if this is a fresh build), that can be done using the rootfssize variable near the top of the run_qemu.sh script. It is currently set to 10G, you can try making it 12G or so.

**Comment by kilobyte** [comment]
Unless you're going to copy/backup the image with a hole-ignorant tool, making the size drastically larger (40G? 100G?) costs nothing as the file will be sparse on the disk.

If discard is enabled, the image file will also require less storage upon guest file deletion, as qemu will translate discard requests into unmapping parts of the image file, thus restoring sparseness.

**Comment by marc-hb** [comment]
Please:
- upgrade to the latest run_qemu
- upgrade Fedora because v39 is not supported anymore
- apply @stellarhopper's suggestions
- re-open if you can still reproduce
