### ISSUE TITLE
‣ Error: Sorry, --without-unified-kernel-images is not supported in UEFI mode on this distro.

### ISSUE THREAD

**Issue by LIUQyou** [pmem/run_qemu#39]
I tried to run it with the run_qemu.sh to build the ubuntu image. So I modified the following inside the run_qemu.sh.
```
: "${distro:=ubuntu}"
: "${rev:=focal}"
```
Then I try the following command in my linux kernel folder:
```
sudo run_qemu.sh --cxl
```
Then I got the following result:
```
‣ Error: Sorry, --without-unified-kernel-images is not supported in UEFI mode on this distro.
```
Could you give me some hints on which part is wrong? Thank you very much

**Comment by stellarhopper** [comment]
What version of mkosi does your distro have? It might be too old for that option.
As a workaround you can comment this line: https://github.com/pmem/run_qemu/blob/main/mkosi.ubuntu.default.tmpl#L12

**Comment by LIUQyou** [comment]
Thanks. I use version 12. After commenting on this. It works

**Comment by shawn8172014** [comment]
遇到同样的问题
