### ISSUE TITLE
ubuntu gdb Segmentation fault 

### ISSUE THREAD

**Issue by shawn8172014** [pmem/run_qemu#41]
run_qemu.sh  --git-qemu --rebuild=none --cxl --cxl-test --cxl-debug --gdb

/usr/local/bin/run_qemu.sh: line 1319: 288649 Segmentation fault      (core dumped) "${qcmd[@]}"

**Comment by shawn8172014** [comment]
help

**Comment by stellarhopper** [comment]
@shawn8172014  are you still seeing this? Can you try with the latest qemu (does your qemu branch have any modifications or was it just upstream?)

**Comment by marc-hb** [comment]
> help

Can't help without versions, detailed reproduction steps and longer logs. That single line is not even enough to tell what is specifically crashing. If it's QEMU then this tracker is not the right place.

**Comment by marc-hb** [comment]
Please:
- reproduce with more recent versions
- share detailed steps and versions
- re-open
