### ISSUE TITLE
sed: can't read ./qbuild/mnt/loader/loader.conf: No such file or directory

### ISSUE THREAD

**Issue by hishine6** [pmem/run_qemu#8]
Hello, 

I am currently trying to apply this script with the following materials.
- Linux: https://git.kernel.org/pub/scm/linux/kernel/git/cxl/cxl.git - tag cxl-for-5.16
- QEMU: https://gitlab.com/bwidawsk/qemu.git - branch cxl-2.0v4
- mkosi: https://github.com/systemd/mkosi - version 12 

Since my host OS is Ubuntu(20.04), I am trying out the recently merged "Add Ubuntu Support" to install ubuntu-bionic(18.04). But I am facing the following error.

After successfully going through "build_kernel" and "make_rootfs" (I have used the command 'sudo run_qemu.sh --cxl --git-qemu') an error occurs during 'update_rootfs_boot_kernel'.  

`sed: can't read ./qbuild/mnt/loader/loader.conf: No such file or directory`

In line 491 of 'run_qemu.sh', there is a reference to '$builddir/mnt/loader/loader.conf'. So to check this out, I have manually mounted the EFI system partition (using losetup, mount) and checked the /mnt/loader directory. It only contained a directory named 'entries'.

I tried to solve this myself, and looked through all the scripts, but I couldn't find any other part where it mounted the EFI system partition rather than 'update_rootfs_boot_kernel'. Could it be because of some sort of mkosi error? 

Thank you for your time.

**Comment by hishine6** [comment]
I have passed on this issue by manually creating a "/mnt/loader/loader.conf" file and running the script again. I am not sure what the future consequences would be, but it looks like it works just fine for now. 

Thank you.

**Comment by stellarhopper** [comment]
@hishine6 It is possible that mkosi doesn't setup systemd-boot for Ubuntu 18.x  - Can you check if using a more recent Ubuntu for the guest helps?

What that part of the script is trying to do is set up standalone booting in the image so it can be used outside of qemu's direct kernel boot. The setup is specific to the systemd-boot bootloader, so maybe if that isn't found, we should warn and continue without the bootable image setup instead of failing.

**Comment by hishine6** [comment]
@stellarhopper Does that mean that in my case, where only using the image to boot through qemu, it won't be a problem? 

Also, I have tried out the guest version to "focal"(20.XX), but unfortunately it returned the same results. 

Based on the advise you have gave me, I have looked into the mkosi(version 12) codes. Searching through the codes using the key word 'systemd-boot', I have found the following code part in "mkosi/mkosi/__init__.py"

```
1645     if args.get_partition(PartitionIdentifier.esp):
1646         # These distros need uefi_stub configured explicitly for dracut to find the systemd-boot uefi stub.
1647         if args.distribution in (Distribution.ubuntu,
1648                                  Distribution.debian,
1649                                  Distribution.mageia,
1650                                  Distribution.openmandriva,
1651                                  Distribution.gentoo):
1652             dracut_dir.joinpath("30-mkosi-uefi-stub.conf").write_text(
1653                 "uefi_stub=/usr/lib/systemd/boot/efi/linuxx64.efi.stub\n"
1654             )
1655 
1656         # efivarfs must be present in order to GPT root discovery work
1657         dracut_dir.joinpath("30-mkosi-efivarfs.conf").write_text(
1658             '[[ $(modinfo -k "$kernel" -F filename efivarfs 2>/dev/null) == /* ]] && add_drivers+=" efivarfs "\n'
1659         )
```

It seems like it needs additional configuration in order to use the systemd-boot in ubuntu. 
I am not 100% sure about this, but judging from that it originally worked for fedora & arch and no on ubuntu I think this was the problem. So, I assume that, like you kindly explained above, the run_qemu.sh should show a warning for 'distro=ubuntu' and continue the script process. 

I hope this makes sense and helps!
Thank you.

**Comment by marc-hb** [comment]
> Since my host OS is Ubuntu(20.04)

Is this still an issue with Ubuntu 22.04? (with mkosi v12)

Support for Ubuntu 24.04 is coming, please help test and review #80

**Comment by marc-hb** [comment]
Please reproduce with more recent versions of everything and re-open.
